class EMSConnectionState(Enum):
    BLE_STATE_CONNECT_NONE = 0
    BLE_STATE_CONNECT_CONNECTING = 1
    BLE_STATE_CONNECT_CONNECTED = 2
    BLE_STATE_CONNECT_CONNECT_FAIL = 3
    BLE_STATE_CONNECT_DISCONNECTED = 4
   
